/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import database.KetNoi;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import process.LopHoc;
import process.LopHocPro;
import java.sql.*;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PHAN ANH TUAN
 */
public class frmLopHoc extends javax.swing.JFrame {

    LopHocPro lpro = new LopHocPro();
    String maLop = "";

    public String getMaLop() {
        return maLop;
    }

    public void setMaLop(String maLop) {
        this.maLop = maLop;
    }

    public frmLopHoc() {
        initComponents();
        hienthi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfmalop = new javax.swing.JTextField();
        jtftenlop = new javax.swing.JTextField();
        jtfgiaovien = new javax.swing.JTextField();
        jbtThem = new javax.swing.JButton();
        jbtSua = new javax.swing.JButton();
        jbtXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtlophoc = new javax.swing.JTable();
        jbtLuu = new javax.swing.JButton();
        jbtHienThi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ma lop");

        jLabel2.setText("ten lop");

        jLabel3.setText("giao vien");

        jbtThem.setText("them");
        jbtThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtThemActionPerformed(evt);
            }
        });

        jbtSua.setText("sua");
        jbtSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSuaActionPerformed(evt);
            }
        });

        jbtXoa.setText("xoa");
        jbtXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtXoaActionPerformed(evt);
            }
        });

        jtlophoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtlophoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtlophocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtlophoc);

        jbtLuu.setText("Lưu");
        jbtLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLuuActionPerformed(evt);
            }
        });

        jbtHienThi.setText("Hiển thị danh sách sinh viên");
        jbtHienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtHienThiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtHienThi))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfgiaovien, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                                    .addComponent(jtftenlop)
                                    .addComponent(jtfmalop)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtLuu)
                                .addGap(41, 41, 41)
                                .addComponent(jbtThem)
                                .addGap(50, 50, 50)
                                .addComponent(jbtSua)
                                .addGap(45, 45, 45)
                                .addComponent(jbtXoa)))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfmalop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtftenlop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfgiaovien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtThem)
                    .addComponent(jbtSua)
                    .addComponent(jbtXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtHienThi)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void hienthi() {
        Connection con = null;
        try {
            con = KetNoi.KetNoiCSDL();
            String col[] = new String[]{"ma lop", "ten lop", "giao vien"};
            DefaultTableModel dtm = new DefaultTableModel(col, 0);
            Object row[];
            List<LopHoc> list = lpro.listLH();
            for (LopHoc l : list) {
                row = new Object[3];
                row[0] = l.getMalop();
                row[1] = l.getTenlop();
                row[2] = l.getGiaovien();
                dtm.addRow(row);
            }
            jtlophoc.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(frmLopHoc.class.getName()).log(Level.SEVERE, null, ex);
        }
        jbtLuu.setEnabled(false);
    }

    public boolean kiemTraMaTrung(String id) {
        for (LopHoc object : lpro.listLH()) {
            if (object.getMalop().equals(id)) {
                return true;
            }
        }
        return false;
    }

    public void themLH() {
        LopHoc l = new LopHoc();
        l.setMalop(jtfmalop.getText());
        l.setTenlop(jtftenlop.getText());
        l.setGiaovien(jtfgiaovien.getText());
        boolean kq = lpro.them(l);
        if (kq) {
            JOptionPane.showMessageDialog(rootPane, "thêm thành công");
        }else{
            JOptionPane.showMessageDialog(rootPane, "mã lớp bạn nhập đã tồn tại", "trùng mã", JOptionPane.WARNING_MESSAGE);
        }
    }

    public void suaLH() {
        LopHoc l = new LopHoc();
        l.setMalop(jtfmalop.getText());
        l.setTenlop(jtftenlop.getText());
        l.setGiaovien(jtfgiaovien.getText());
        boolean kq = lpro.sua(l);
        if (kq) {
            JOptionPane.showMessageDialog(rootPane, "sửa thành công");
        }
    }
    
    public void xoaLH(){
        int dongChon = jtlophoc.getSelectedRow();
        String maLopHoc = "" + jtlophoc.getValueAt(dongChon, 0);
        boolean kq = lpro.xoa(maLopHoc);
        if(kq){
            JOptionPane.showMessageDialog(rootPane, "xóa thành công");
        }else {
            JOptionPane.showMessageDialog(rootPane, "Lớp học đang có sinh viên", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }
    }
   
    private void jbtThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtThemActionPerformed
        if(jbtThem.getText().equalsIgnoreCase("Hủy")){
            jbtSua.setEnabled(true);
            jbtXoa.setEnabled(true);
            jbtThem.setText("Thêm");
            jtfmalop.setText("");
            jtftenlop.setText("");
            jtfgiaovien.setText("");
        }else{
            jbtSua.setEnabled(false);
            jbtXoa.setEnabled(false);
            jbtThem.setText("Hủy");
            jbtLuu.setEnabled(true);
        }
        
    }//GEN-LAST:event_jbtThemActionPerformed

    private void jbtHienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtHienThiActionPerformed
        frmSinhVien f = new frmSinhVien();
        f.setVisible(true);
    }//GEN-LAST:event_jbtHienThiActionPerformed

    private void jbtLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLuuActionPerformed
        if(jbtThem.getText().equalsIgnoreCase("Hủy")){
            themLH();
        }else if(jbtSua.getText().equalsIgnoreCase("Hủy")){
            suaLH();
        }
    }//GEN-LAST:event_jbtLuuActionPerformed

    private void jbtSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSuaActionPerformed
        if(jbtThem.getText().equalsIgnoreCase("Hủy")){
            jbtSua.setEnabled(true);
            jbtXoa.setEnabled(true);
            jbtSua.setText("sua");
            jtfmalop.setText("");
            jtftenlop.setText("");
            jtfgiaovien.setText("");
        }else{
            jbtSua.setEnabled(false);
            jbtXoa.setEnabled(false);
            jbtSua.setText("Hủy");
            jbtLuu.setEnabled(true);
        }
    }//GEN-LAST:event_jbtSuaActionPerformed

    private void jbtXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtXoaActionPerformed
        xoaLH();
    }//GEN-LAST:event_jbtXoaActionPerformed

    private void jtlophocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtlophocMouseClicked
        int r = jtlophoc.getSelectedRow();
        String ma = jtlophoc.getValueAt(r, 0).toString();
        String ten = jtlophoc.getValueAt(r, 1).toString();
        String gv = jtlophoc.getValueAt(r, 2).toString();
        jtfmalop.setEnabled(false);
        jtfmalop.setText(ma);
        jtftenlop.setText(ten);
        jtfgiaovien.setText(gv);
    }//GEN-LAST:event_jtlophocMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLopHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLopHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLopHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLopHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLopHoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtHienThi;
    private javax.swing.JButton jbtLuu;
    private javax.swing.JButton jbtSua;
    private javax.swing.JButton jbtThem;
    private javax.swing.JButton jbtXoa;
    private javax.swing.JTextField jtfgiaovien;
    private javax.swing.JTextField jtfmalop;
    private javax.swing.JTextField jtftenlop;
    private javax.swing.JTable jtlophoc;
    // End of variables declaration//GEN-END:variables
}
