/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import database.KetNoi;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import process.SinhVien;
import process.SinhVienPro;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author PHAN ANH TUAN
 */
public class frmSinhVien extends javax.swing.JFrame {

    SinhVienPro svPro = new SinhVienPro();

    public void hienthi() {
        try {
            Connection con = KetNoi.KetNoiCSDL();
            String[] colTieuDe = new String[]{"Mã sinh viên", "Tên sinh viên", "Email", "Địa chỉ"};
            DefaultTableModel dtm = new DefaultTableModel(colTieuDe, 0);
            Object o[] = null;
            List<SinhVien> listSV = svPro.layDanhSachSinhVien();
            for (SinhVien x : listSV) {
                o = new Object[4];
                o[0] = x.getMasv();
                o[1] = x.getTensv();
                o[2] = x.getEmail();
                o[3] = x.getDiachi();
                dtm.addRow(o);
            }
            jtsv.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(frmSinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void themSV() {
        SinhVien sv = new SinhVien();
        sv.setMasv(jtfmasv.getText());
        sv.setTensv(jtften.getText());
        sv.setEmail(jtfemail.getText());
        sv.setDiachi(jtfdiachi.getText());
        sv.setMalop(jcbMaLop.getSelectedItem().toString()); 
        if(sv.getMasv().length() == 0 || sv.getTensv().length() == 0 || sv.getEmail().length() == 0 || sv.getDiachi().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Chưa nhập đủ dữ liệu");          
        }else {
            boolean kq = svPro.them(sv);
            if (kq) {
                JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
            } else {
                JOptionPane.showMessageDialog(rootPane, "mã sinh viên đã tồn tại", "trùng mã", JOptionPane.WARNING_MESSAGE);
            }
        }
        
    }

    public void suaSV() {
        SinhVien sv = new SinhVien();
        sv.setMasv(jtfmasv.getText());
        sv.setTensv(jtften.getText());
        sv.setEmail(jtfemail.getText());
        sv.setDiachi(jtfdiachi.getText());
        sv.setMalop(jcbMaLop.getSelectedItem().toString());
        boolean kq = svPro.sua(sv);
        if (kq) {
            JOptionPane.showMessageDialog(rootPane, "Sửa thành công");
        }
    }

    public void xoaSV() {
        int dongChon = jtsv.getSelectedRow();
        String ma = "" + jtsv.getValueAt(dongChon, 0);
        boolean kq = svPro.xoa(ma);
        if (kq) {
            JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
        }
    }

    public void truyenDuLieuTuDBVaoComboBox() {
        try {
            Connection con = KetNoi.KetNoiCSDL();
            String sql = "select *from lophoc";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                jcbMaLop.addItem(rs.getString("malop"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmSinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public frmSinhVien() {
        initComponents();
        hienthi();
        truyenDuLieuTuDBVaoComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfmasv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtften = new javax.swing.JTextField();
        jtfemail = new javax.swing.JTextField();
        jtfdiachi = new javax.swing.JTextField();
        jbtxoa = new javax.swing.JButton();
        jbtthoat = new javax.swing.JButton();
        jbtsua = new javax.swing.JButton();
        jbtthem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtsv = new javax.swing.JTable();
        jbtLuu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jcbMaLop = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ma sv");

        jLabel2.setText("ten");

        jLabel3.setText("email");

        jLabel4.setText("dia chi");

        jbtxoa.setText("xoa");
        jbtxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtxoaActionPerformed(evt);
            }
        });

        jbtthoat.setText("thoat");
        jbtthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtthoatActionPerformed(evt);
            }
        });

        jbtsua.setText("sua ");
        jbtsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtsuaActionPerformed(evt);
            }
        });

        jbtthem.setText("them");
        jbtthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtthemActionPerformed(evt);
            }
        });

        jtsv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtsv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtsvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtsv);

        jbtLuu.setText("Lưu");
        jbtLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLuuActionPerformed(evt);
            }
        });

        jLabel5.setText("ma lop");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(48, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(62, 62, 62))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfmasv)
                            .addComponent(jtften)
                            .addComponent(jtfemail)
                            .addComponent(jtfdiachi, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(jcbMaLop, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtthoat, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtxoa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtsua, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtthem, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtLuu, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfmasv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtthem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtften, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtsua)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jtfemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtxoa))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtthoat)
                    .addComponent(jtfdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtLuu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtthemActionPerformed

        if (jbtthem.getText().equalsIgnoreCase("Hủy")) {
            jtfmasv.setText("");
            jtften.setText("");
            jtfdiachi.setText("");
            jtfemail.setText("");
            jbtthem.setText("Thêm");
            jbtsua.setEnabled(true);
            jbtxoa.setEnabled(true);
        } else {
            jbtLuu.setEnabled(true);
            jbtsua.setEnabled(false);
            jbtxoa.setEnabled(false);
            jbtthem.setText("Hủy");
        }

    }//GEN-LAST:event_jbtthemActionPerformed

    private void jbtsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtsuaActionPerformed
        
        if (jbtsua.getText().equalsIgnoreCase("Hủy")) {
            jtfmasv.setText("");
            jtften.setText("");
            jtfdiachi.setText("");
            jtfemail.setText("");
            jbtsua.setText("sua");
            jbtsua.setEnabled(true);
            jbtxoa.setEnabled(true);
        } else {
            jbtLuu.setEnabled(true);
            jbtsua.setEnabled(false);
            jbtxoa.setEnabled(false);
            jbtsua.setText("Hủy");
        }
    }//GEN-LAST:event_jbtsuaActionPerformed

    private void jbtxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtxoaActionPerformed
        xoaSV();
    }//GEN-LAST:event_jbtxoaActionPerformed

    private void jbtLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLuuActionPerformed
        if (jbtthem.getText().equalsIgnoreCase("Hủy")) {
            themSV();
        } else if (jbtsua.getText().equalsIgnoreCase("Hủy")) {
            suaSV();
        }
    }//GEN-LAST:event_jbtLuuActionPerformed

    private void jtsvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtsvMouseClicked
        int r = jtsv.getSelectedRow();
        String ma = jtsv.getValueAt(r, 0).toString();
        String ten = jtsv.getValueAt(r, 1).toString();
        String mail = jtsv.getValueAt(r, 2).toString();
        String dc = jtsv.getValueAt(r, 3).toString();
        SinhVien sv = new SinhVien();
        jtfmasv.setText(ma);
        jtften.setText(ten);
        jtfemail.setText(mail);
        jtfdiachi.setText(dc);
        jcbMaLop.setSelectedItem(jtsv.getValueAt(r, NORMAL).toString());
    }//GEN-LAST:event_jtsvMouseClicked

    private void jbtthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtthoatActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbtthoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtLuu;
    private javax.swing.JButton jbtsua;
    private javax.swing.JButton jbtthem;
    private javax.swing.JButton jbtthoat;
    private javax.swing.JButton jbtxoa;
    private javax.swing.JComboBox<String> jcbMaLop;
    private javax.swing.JTextField jtfdiachi;
    private javax.swing.JTextField jtfemail;
    private javax.swing.JTextField jtfmasv;
    private javax.swing.JTextField jtften;
    private javax.swing.JTable jtsv;
    // End of variables declaration//GEN-END:variables
}
